### ISSUE TITLE
Workshop presentation slides

### ISSUE THREAD

**Issue by vkolencik** [james-jory/segment-personalize-workshop#16]
Hi, do you think it's possible to add workshop presentation slides to this repo?

**Comment by james-jory** [comment]
I believe the slides or a link to the slides was sent out in a follow-up email for the workshop from Segment. If you didn't get the email, let me know if it's okay to email the deck to your email address on your github profile and will send directly.

**Comment by vkolencik** [comment]
I searched through the emails once again and only found a follow-up email with feedback link. If you could send it to the address in my github profile that would be great, thanks! V.
